### ISSUE TITLE
[1.18.2] creating new world goes poopie

### ISSUE THREAD

**Issue by Cixon** [Hipposgrumm/armor-trims#13]
Context: I just updated your recent 1.18 update and the JEI plugins used seems to freeze the world create phase.

Line (2,169):
[latest.log](https://github.com/Hipposgrumm/armor-trims/files/11713662/latest.log)

I believe it has something to do with your mod and Iron's Spellbook
https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

**Comment by Hipposgrumm** [comment]
I will look at it when I can.

**Comment by Hipposgrumm** [comment]
I can't seem to be able to recreate the bug. Can you send me the current version of the pack you are working on (like, the version that is having problems)?

**Comment by Cixon** [comment]
https://legacy.curseforge.com/minecraft/modpacks/legacy-forge/files/4575021

**Comment by Hipposgrumm** [comment]
I'm not having any problem. I only see my mod works and there's chonky rabbit.
![2023-06-11_16 41 01](https://github.com/Hipposgrumm/armor-trims/assets/60556345/dc8a00dc-a95e-4605-b7e4-c9b723282bf1)

Can you tell me what I must do to reproduce the issue?

**Comment by Cixon** [comment]
i'm going to upload a version with this issue to you personally before uploading to cf

**Comment by Hipposgrumm** [comment]
If you want we can converse on Discord. Is PMing a thing on GitHub?

**Comment by Cixon** [comment]
send me discord please

**Comment by Hipposgrumm** [comment]
I'll delete the message after I receive your DM.
Hipposgrumm#9926

**Comment by Cixon** [comment]
ticket outsourced, new issue arised. title no longer relevant.
