### ISSUE TITLE
[SUGGESTION] Stackable armor trims!

### ISSUE THREAD

**Issue by Wanderer70** [Hipposgrumm/armor-trims#14]
**Allows for stacking of all the smithing templates and color palettes!**
This could be enabled/disabled via config for those who want a more vanilla-ish aesthetic.
There are already mods like this for 1.20 and so having such an option in this mod would be a really cool addition!)

**Comment by Hipposgrumm** [comment]
Maybe someday but it's not really at the top of my list of priorities at the moment.

**Comment by Hipposgrumm** [comment]
After thinking about it for a while, I decided that I’m not going to add stackable trims in my mod. The developer of the Stackable Trims mod can add compatibility if they want to, but it’s not something I’m going to do in this mod.
