### ISSUE TITLE
Adding Russian Translation

### ISSUE THREAD

**Issue by PortalRU** [Hipposgrumm/armor-trims#16]
Hi. 
Could you add Russian localization for your mod?

Russian Language pack: https://github.com/PortalRU/armor-trim_language_pack_RU

**Comment by PortalRU** [comment]
Thanks for the comments. Everything has been fixed.

1.18.2:https://github.com/PortalRU/armor-trims_language_pack_RU/tree/1.18.2
1.19.2: https://github.com/PortalRU/armor-trims_language_pack_RU/tree/1.19.2

**Comment by Hipposgrumm** [comment]
Added in v1.2.1.
