### ISSUE TITLE
Green Trim Overlay on Mobs and Players

### ISSUE THREAD

**Issue by XAURAVUS** [Hipposgrumm/armor-trims#17]
As seen in the attached screenshot, a strange green armor trim appears on players at seemingly random. Reloading the instance clears the issue, but the bug returns with due time. This trim has also been reported on mobs such as zombies and skeletons by myself and others on a server I play on. I would attach a crash report, but this bug does not cause a crash.
![image](https://github.com/Hipposgrumm/armor-trims/assets/82698242/08154cfa-b6ff-408b-bf81-f91c2b2c3865)

**Comment by Hipposgrumm** [comment]
About how long does it take to show up?
Are there any trimmed items nearby?

**Comment by Syclusion** [comment]
Its rubidium causing it on my end

**Comment by Hipposgrumm** [comment]
_What the heck is Rubidium screwing up this time and how the heck does it even…_

**Comment by Hipposgrumm** [comment]
Wait, do you have Oculus installed? If so, this links back to #9 which leads to [Asek3/Oculus#369](https://github.com/Asek3/Oculus/issues/369).

**Comment by Syclusion** [comment]
No, I removed everything except rubidium and this

**Comment by XAURAVUS** [comment]
> About how long does it take to show up?
> Are there any trimmed items nearby?

This bug, from my experience, only appears after roughly an hour of gameplay at the very least.

Neither I nor the players in my server have trimmed a single piece of armor yet, but we do have armor trims in our possession as items.

Also, I do not have images of these instances at the moment, but I have seen this bug appear on armor stands as well.

**Comment by Hipposgrumm** [comment]
Then it probably happens with Zombies, Skeletons, Piglins, etc.

**Comment by PINPAL** [comment]
Is there a solution to this while keeping Rubidium?

**Comment by Hipposgrumm** [comment]
Apparently, the bug has nothing to do with Rubidium and I can’t figure out how to reproduce it. I am really starting to lose my mind here.

**Comment by PINPAL** [comment]
> Apparently, the bug has nothing to do with Rubidium and I can’t figure out how to reproduce it. I am really starting to lose my mind here.

I get it everytime if you want some helping debugging? I can provide logs or anything else you need?

**Comment by Hipposgrumm** [comment]
Fixed in 1.3.
