### ISSUE TITLE
Mixin Crash with Rubidium

### ISSUE THREAD

**Issue by WenXin20** [Hipposgrumm/armor-trims#2]
```
Minecraft v1.19.2
Forge v43.2.7
Armor Trims v1.1
```

Hello, I installed the mod, but it has  a mixin crash during launch
[Crash Report](https://gist.github.com/WenXin20/265d86f35a51764f3cee76d6e5c66356#file-armor_trims_crash-txt-L1217)

**Comment by Hipposgrumm** [comment]
It seems to be a compatibility issue with Radium. I’ll fix it tomorrow.

**Comment by WenXin20** [comment]
I have rubidium installed, but not Radium

**Comment by Hipposgrumm** [comment]
> I have rubidium installed, but not Radium

Whatever it’s called.

**Comment by Hipposgrumm** [comment]
Fixed version is being released now.
