### ISSUE TITLE
Unable to Launch in modded Environment

### ISSUE THREAD

**Issue by Atlantispy** [Hipposgrumm/armor-trims#20]
[latest.log](https://github.com/Hipposgrumm/armor-trims/files/11898300/latest.log)

Latest forge 1.18.2, latest mod version, extensive modlist (404 mods).

Happy to work with you to find what's causing the issue.

[crash-2023-06-28_18.04.48-fml.txt](https://github.com/Hipposgrumm/armor-trims/files/11898306/crash-2023-06-28_18.04.48-fml.txt)

Can launch game but on trying to enter a world it breaks.

**Comment by Hipposgrumm** [comment]
Try removing End’s Phantasm. It seems to be causing Out Of Bounds errors.

**Comment by Atlantispy** [comment]
[latest.log](https://github.com/Hipposgrumm/armor-trims/files/11898953/latest.log)

New log upon making that change

**Comment by Hipposgrumm** [comment]
I don't think this issue has anything to do with Armor Trims. If you can show that it is because of this mod, I will reopen the issue.
