### ISSUE TITLE
All upgrade recipes work independently of the upgrade templates.

### ISSUE THREAD

**Issue by QwertRvg** [Hipposgrumm/armor-trims#23]
![2023-07-03_17 51 47](https://github.com/Hipposgrumm/armor-trims/assets/89683173/2f0c9778-e787-412f-a94d-596567059630)
Additional Additions allows creating Gilded Netherite using a Golden Ring.

![2023-07-03_17 51 53](https://github.com/Hipposgrumm/armor-trims/assets/89683173/91d0b3de-26f2-4c50-bd6e-f4232ac00bd5)
But for some reason with the Armor Trims mod, it is both possible to upgrade with and without the Netherite Upgrade.
Creating the Gilded Netherite set is not upgrading to Netherite, so it shouldn't work with the Netherite Upgrade item. It should only work without it

**Comment by Hipposgrumm** [comment]
So netherite upgrading is just weird then I guess.
Now that I can confirm this I can investigate it further.

**Comment by Hipposgrumm** [comment]
I guess this ties into #29. Now I know that I probably need to invert a boolean value now.

**Comment by Hipposgrumm** [comment]
Also, you can add custom upgrade templates using the mod’s built-in API (assuming it works).

**Comment by Hipposgrumm** [comment]
So apparently it’s not as simple as flipping a value. I’ll probably need to rewrite the whole system.

**Comment by QwertRvg** [comment]
Thank you so much! The issue was fixed with the latsest update
