### ISSUE TITLE
[SUGGESTION} Ability to tweak brightness and/or color of armor trims

### ISSUE THREAD

**Issue by JustVibin247** [Hipposgrumm/armor-trims#25]
I have recently noticed that the armor trims look extremely dark compared to their vanilla counterparts. So to fix that, it would be cool if there were a config value to change the brightness and/or color of an armor trim to make them look much more like their vanilla counterpart. (p.s. I know about the brighten trim colors option in the config but even with it on it the trims are still much darker than their vanilla counterparts)

Comparison below (top is vanilla and bottom is modded):
![image](https://github.com/Hipposgrumm/armor-trims/assets/72247863/603f92a5-7062-44b9-b517-216af0191c4f)
![image](https://github.com/Hipposgrumm/armor-trims/assets/72247863/4972e651-1bb4-4261-aee8-2ce6ea6bffd2)

**Comment by Hipposgrumm** [comment]
Maybe I’ll replace try brighten colors with a darkness tolerance value.
