### ISSUE TITLE
Server seems to ignore config to make items Untrimmable

### ISSUE THREAD

**Issue by TorchTheDragon** [Hipposgrumm/armor-trims#26]
Exactly as the title states. here is an image of an item still having the Armor Trim tab and still allowing me trim it, even though I have disabled the item in the configs.

![image](https://github.com/Hipposgrumm/armor-trims/assets/72819066/2c034fb4-ab18-4124-b0b2-d905e1ce992a)![image](https://github.com/Hipposgrumm/armor-trims/assets/72819066/e1c83ec9-21a4-4d9e-ad94-1484c1985415)

Also, just found out that even though I have the "Don't consume Trim" option enabled, it still did.

I have also attached the config file to show that it is in there. The specific item used in the image is "weavers_cosmetics:gilded_knights_armour_helmet". Also, I just converted the .toml to a .txt cuz GitHub don't like it
[armor_trims.toml.txt](https://github.com/Hipposgrumm/armor-trims/files/12017744/armor_trims.toml.txt)

**Comment by TorchTheDragon** [comment]
Admittedly, it could be other mods in the pack, though idk what would prevent the reading of a config.

**Comment by TorchTheDragon** [comment]
Using Create, it also shows that the field is empty for Untrimmable Items, yet in the server file manager, it isn't. It is a very long list.

Create Config Editor:
![image](https://github.com/Hipposgrumm/armor-trims/assets/72819066/91d4565f-427a-4a7b-854f-db72abd06fd3)

Server File Manager:
![image](https://github.com/Hipposgrumm/armor-trims/assets/72819066/c38a8cb8-1330-4939-9b44-b40a4eb8980b)
![image](https://github.com/Hipposgrumm/armor-trims/assets/72819066/f8d039b2-1c07-4d1b-b6d0-678dd625b3c5)

**Comment by Hipposgrumm** [comment]
Modpack Maketh Mode doesn’t exactly work and I am aware of this.

**Comment by TorchTheDragon** [comment]
One thing that could be noted is it does work fine when in singleplayer

**Comment by TorchTheDragon** [comment]
Also, those armors in that list are just straight up incompatible, hence why I put the list there on the server. If ya want, I can go on a grind and try to find as many as possible so there is a list available. Two mods I know that are fully incompatible are Immersive Armors and Weavers Cosmetics

**Comment by Hipposgrumm** [comment]
You don’t need to go on a giant goose chase. I’ll probably add a feature where custom models will refuse to be trimmed based on what the client says if it’s a custom model.

**Comment by Hipposgrumm** [comment]
I figured out why this doesn't work. Apparently I forgot to assign everything to everything.

**Comment by PINPAL** [comment]
Is this fixed? Also encountering the same issue and was hoping I could prevent Create's backtank/diving gear from being trimmed as it causes you to be wearing a giant purple box.
![image](https://github.com/Hipposgrumm/armor-trims/assets/18197217/846deed3-a303-4f8a-ab9b-0acd30ac490a)

My config:
```toml
# Disable trimming for any items that don't work when trimmed.
"Untrimmable Items" = [
	"create:netherite_backtank",
	"create:copper_backtank",
	"create:netherite_diving_boots",
	"create:netherite_diving_helmet",
	"create:copper_diving_boots",
	"create:copper_diving_helmet",
	"ironjetpacks:jetpack",
	"railways:white_conductor_cap",
	"railways:orange_conductor_cap",
	"railways:magenta_conductor_cap",
	"railways:light_blue_conductor_cap",
	"railways:yellow_conductor_cap",
	"railways:lime_conductor_cap",
	"railways:pink_conductor_cap",
	"railways:gray_conductor_cap",
	"railways:light_gray_conductor_cap",
	"railways:cyan_conductor_cap",
	"railways:purple_conductor_cap",
	"railways:blue_conductor_cap",
	"railways:brown_conductor_cap",
	"railways:green_conductor_cap",
	"railways:red_conductor_cap",
	"railways:black_conductor_cap",
	"minecraft:shulker_shell",
]
```
