### ISSUE TITLE
[1.19.2] Can't load into world with JEI and this mod installed together.

### ISSUE THREAD

**Issue by murao-kun** [Hipposgrumm/armor-trims#3]
If you install JEI along with this mod, you will not be able to load in world.

**Comment by murao-kun** [comment]
MInecraft 1.19.2
JEI 11.6.0.1015
Trims 1.1.1

**Comment by Hipposgrumm** [comment]
Can you send the debug.log?
What do you mean by not loading in? Is it a crash?

**Comment by murao-kun** [comment]
Sure. It is not a crash, just infinite loading with a text "Joining world..".
But the game is not crashing.
[debug.log](https://github.com/Hipposgrumm/armor-trims/files/11548490/debug.log)

**Comment by murao-kun** [comment]
Also that is what console output say on that loading.
![image](https://github.com/Hipposgrumm/armor-trims/assets/110398598/4fb68d76-452f-4a49-86f7-4ec821eb8889)

**Comment by Hipposgrumm** [comment]
Works perfectly fine for me.
Have you tried _waiting_? 🤯

**Comment by Hipposgrumm** [comment]
Works perfectly fine for me.
Have you tried waiting? 🤯

**Comment by murao-kun** [comment]
I should try addons too. Waiting is not helping. I was testing for about half an hour. I will dog more into that issue.

**Comment by Hipposgrumm** [comment]
This is now being dealt with in #6. If you have any more info you are welcome to put it there.
