### ISSUE TITLE
Option for Vanilla like slot behavior (Middleslot and Template outlines)

### ISSUE THREAD

**Issue by JustKenjiX** [Hipposgrumm/armor-trims#31]
Is it possible to add template outlines in the second slot like in vanilla, so you know that you need to use templates for the trim or upgrade.

I know it is by design but would love to have a config option for the middle slot always be there instead of only show when insert a template. Thats very confusing for new players on a server who don't know that mechanic.

**Comment by Hipposgrumm** [comment]
I decided to just move some things around and make the slot always shown. This change will release in the next version.
