### ISSUE TITLE
ArmorTrims causes JEI to fall into a infinite loop and never finish loading

### ISSUE THREAD

**Issue by StShAzzy** [Hipposgrumm/armor-trims#32]
[2024-01-04-3.log](https://github.com/Hipposgrumm/armor-trims/files/13835691/2024-01-04-3.log)

it might be a compatibility issue with the modpack i'm running, but i can't be sure of that, so if you wish to debug this mess further than i did

[here the modpack](https://drive.google.com/file/d/1j5M7c3QFvUqV1jEkcQYqoA23l-uqo6mr/view?usp=drive_link)
[if you hate google here's a mirror temporary mirror](https://send.vis.ee/download/d7cdd224e9a67734/#7_efDInu-iWtJg9N4h4Uhg)

**Comment by Hipposgrumm** [comment]
It's a known issue that the mod causes JEI to take a while to load (especially when there are a lot of items registered). It should be getting fixed when the new version comes out (whenever it does).

Additionally, (unrelated) I don't hate using Google Drive. In fact, I save my modding projects on Google Drive. (I feel like it's convenient but almost every modder I've talked to absolutely hates it.)

**Comment by Hipposgrumm** [comment]
Closing as duplicate for now until you deduce that the game actually *never* loads (after waiting a few hours or something).
Also can you send the pack as a CurseForge or Modrinth pack? (I'm not usually this cautious but who knows if you've hidden a virus inside.)

**Comment by StShAzzy** [comment]
i don't have an account on both i don't really think i can, as i expect it to ask me for microsoft or mojang account, that might be just me overthinking, i wouldn't put a virus in that if that's of your concern, if you want to, you can add me on discord and i can show you it working on my computer

**Comment by Hipposgrumm** [comment]
There's a pretty good chance this is being fixed in the next update (which will hopefully come out some time this year).
