### ISSUE TITLE
Infinite Loading Screen in modded Pack

### ISSUE THREAD

**Issue by SugarDaddii** [Hipposgrumm/armor-trims#34]
Whenever i try to add this mod to my Modpack and want to join a new world or a old world i get in a loading screen which isnt endling at all....so i cant tell if its crashing or doing stuff

is this a common bug or soing i something wrong?
[latest.log](https://github.com/Hipposgrumm/armor-trims/files/14202290/latest.log)
i can give you my log 

greeting

**Comment by Hipposgrumm** [comment]
Duplicate of #6 which should hopefully be fixed in the new update whenever that comes out.
