### ISSUE TITLE
[Feature Request] Allow Custom Trimming for Items

### ISSUE THREAD

**Issue by Apollounknowndev** [Hipposgrumm/armor-trims#4]
Hello, I develop the Trimmable Tools mod and was looking into if it was possible to backport it to previous versions using this mod. However, it appears that the check for items that can be trimmed is just checking for an ArmorItem. Could this be extended to use an item tag so other mods (like mine) can add new items that can be trimmed?

**Comment by Hipposgrumm** [comment]
You can use gg.hipposgrumm.armor_trims.util.LargeItemList#getAllTrimmable() to get all trimmable items.

**Comment by Hipposgrumm** [comment]
You can use gg.hipposgrumm.armor_trims.util.LargeItemList#getAllTrimmable() to get all trimmable items.

**Comment by Hipposgrumm** [comment]
I have plans for this in the future. However I won't be implementing it now. (You can mixin the new smithing logic class for now.)

**Comment by Hipposgrumm** [comment]
I _think_ I have it working.
