### ISSUE TITLE
[1.19.2] Significant fps drop near armor stands after installing this mod.

### ISSUE THREAD

**Issue by MykolaHamster** [Hipposgrumm/armor-trims#5]
Before installing trims 1.1.1:
![2023-05-24_15 47 07](https://github.com/Hipposgrumm/armor-trims/assets/124202878/3c9f3bc7-afba-4f2a-a261-3598711e9a57)
After:
![2023-05-24_15 51 09](https://github.com/Hipposgrumm/armor-trims/assets/124202878/67e663b7-f6c2-48a4-90ff-dbbe1e1fd226)

Other mods used: Rubidium-0.6.2a, Rubidium_extras-1.19.2_v1.3.2
[debug.log](https://github.com/Hipposgrumm/armor-trims/files/11555034/debug.log)

**Comment by Hipposgrumm** [comment]
Can you see if removing Rubidium Extras and then Rubidium fixes the problem?

**Comment by MykolaHamster** [comment]
Removing rubidium does not fix the problem.
![2023-05-24_16 47 14](https://github.com/Hipposgrumm/armor-trims/assets/124202878/35b2705a-dcfb-4fda-b132-8e8f7731053a)

This number of armor stands is needed to demonstrate the problem.
In my modpack, only seven armor stands are enough to lower fps to 20.

**Comment by Hipposgrumm** [comment]
I am not noticing any significant drop from the 30 I usually have.
If you would send the modpack that is having problems I will gladly reopen the issue.
![2023-05-25_17 42 29](https://github.com/Hipposgrumm/armor-trims/assets/60556345/76a96da7-147f-4d73-a273-003e03ec6095)

**Comment by MykolaHamster** [comment]
Problem happens with some entities too, like piglin. Tested on clear forge 43.2.11 with and without trims backport.

26 piglins without trims backport:
 ![2023-05-26_12 40 42](https://github.com/Hipposgrumm/armor-trims/assets/124202878/12b9f7ae-4d6d-4129-b651-4b02eb0f3c64)
 
 With:
 ![2023-05-26_12 43 17](https://github.com/Hipposgrumm/armor-trims/assets/124202878/ba2b2b4d-6603-4f06-b96e-4725f8a74db1)

Can you reproduce this?

**Comment by Hipposgrumm** [comment]
I assume it affects any entity that wears armor (including players).
I will join Hypixel with and without the mod and see the FPS difference. And I won’t run Fortnite in the background which might help.

**Comment by Hipposgrumm** [comment]
My check for custom model loaded the model every frame because I forgot to cache stuff.

**Comment by MykolaHamster** [comment]
Sadly, bug still persists in version 1.2. Same perfomance as on 1.1.1
![2023-06-09_20 38 37](https://github.com/Hipposgrumm/armor-trims/assets/124202878/2f8cda59-be42-442c-9f92-e68ccd1c954e)
![2023-06-09_20 40 45](https://github.com/Hipposgrumm/armor-trims/assets/124202878/d32f8a61-a321-4661-9c74-2dcc28b0c4e4)

**Comment by Hipposgrumm** [comment]
This hopefully will be fixed in a future version that I hopefully figure out how to add renderlayers dynamically and get them working.

**Comment by MykolaHamster** [comment]
I guess it's fixed in 1.3
![2023-06-29_12 47 36](https://github.com/Hipposgrumm/armor-trims/assets/124202878/433d0692-0514-41c2-ad62-bb6f044d9c3b)

**Comment by Hipposgrumm** [comment]
![B6E7AAB7-1AEE-4183-B133-007191334B7A](https://github.com/Hipposgrumm/armor-trims/assets/60556345/44186df2-4787-4915-aa30-04a56245ff6b)
