### ISSUE TITLE
just hangs when loading world for first time

### ISSUE THREAD

**Issue by cosmoderp** [Hipposgrumm/armor-trims#8]
I tried to add this to the ATM8 modpack for my personal enjoyment and its just hangs trying to register this mod.  Probably some incompatibility but there are so many its hard to determine which mod it would be.

**Comment by Hipposgrumm** [comment]
The issue is probably linked to CraftTweaker, which is already being tracked in #6.
Additionally, you probably shouldn’t add extra mods to an established modpack unless you know what you are doing because it could ruin the chemistry of the pack.
